[package]
name = "authsudo"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "authsudo"
path = "src/main.rs"

[dependencies]
authd-protocol = { path = "../protocol" }
libc = "0.2"
pam = "0.8"
rpassword = "7"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
users = "0.11"
